/-
  Paper 18: Standard Model Yukawa RG — Definitions
  Part of the Constructive Calibration Programme

  This module defines the Standard Model one-loop beta function coefficients
  for the third-generation Yukawa couplings (y_t, y_b, y_τ) and the gauge
  couplings (g₁, g₂, g₃), as rational numbers.

  The key structural property is that all beta functions are polynomial in
  the couplings with rational coefficients. At finite loop order, the RG
  evolution is therefore a polynomial ODE system — computable by Picard
  iteration over ℚ without any omniscience principle (BISH).

  References:
  - Machacek & Vaughn, Nucl. Phys. B 236 (1984) 221 [one-loop beta functions]
  - PDG 2024 [observed coupling values at M_Z]
-/

import Mathlib.Data.Rat.Defs
import Mathlib.Tactic

/-! ## One-loop gauge beta function coefficients

The one-loop gauge coupling RG equations are:
  16π² dg_i/dt = b_i · g_i³
where b_i are the one-loop coefficients.
-/

/-- One-loop coefficient for U(1)_Y: b₁ = 41/6 > 0 (not asymptotically free). -/
def b₁ : ℚ := 41 / 6

/-- One-loop coefficient for SU(2)_L: b₂ = -19/6 < 0 (asymptotically free). -/
def b₂ : ℚ := -19 / 6

/-- One-loop coefficient for SU(3)_c: b₃ = -7 < 0 (asymptotically free). -/
def b₃ : ℚ := -7

/-! ## One-loop Yukawa beta function coefficients

The one-loop third-generation Yukawa beta functions are:
  16π² dy_t/dt = y_t · F_t(y², g²)
  16π² dy_b/dt = y_b · F_b(y², g²)
  16π² dy_τ/dt = y_τ · F_τ(y², g²)

where F_f is a polynomial in y² and g² with rational coefficients.
The crucial structural property is that each beta function is
*multiplicative* in y_f: ḟ_f = y_f · (polynomial in other couplings).

This means ratio betas ṙ = d(y_f/y_t)/dt = r · (F_f - F_t) inherit
the polynomial structure, and fixed points of the ratio flow are
determined by F_f - F_t = 0.
-/

/-- Coefficients for the top Yukawa beta function:
    F_t = (9/2)y_t² + (3/2)y_b² + y_τ² - (17/12)g₁² - (9/4)g₂² - 8g₃²
    Returns (c_yt², c_yb², c_yτ², c_g₁², c_g₂², c_g₃²). -/
def topCoeffs : ℚ × ℚ × ℚ × ℚ × ℚ × ℚ :=
  (9/2, 3/2, 1, -17/12, -9/4, -8)

/-- Coefficients for the bottom Yukawa beta function:
    F_b = (3/2)y_t² + (9/2)y_b² + y_τ² - (5/12)g₁² - (9/4)g₂² - 8g₃²
    Returns (c_yt², c_yb², c_yτ², c_g₁², c_g₂², c_g₃²). -/
def bottomCoeffs : ℚ × ℚ × ℚ × ℚ × ℚ × ℚ :=
  (3/2, 9/2, 1, -5/12, -9/4, -8)

/-- Coefficients for the tau Yukawa beta function:
    F_τ = 3y_t² + 3y_b² + (5/2)y_τ² - (15/4)g₁² - (9/4)g₂² + 0·g₃²
    Returns (c_yt², c_yb², c_yτ², c_g₁², c_g₂², c_g₃²). -/
def tauCoeffs : ℚ × ℚ × ℚ × ℚ × ℚ × ℚ :=
  (3, 3, 5/2, -15/4, -9/4, 0)

/-! ## Difference coefficients for ratio betas

For the ratio r_b = y_b/y_t, the ratio beta is:
  ṙ_b = r_b · (F_b - F_t)

The coefficients of (F_b - F_t) determine the sign of the ratio flow.
Similarly for r_τ = y_τ/y_t.
-/

/-- F_b - F_t coefficient differences.
    (c_yt², c_yb², c_yτ², c_g₁², c_g₂², c_g₃²) -/
def diffCoeffs_bt : ℚ × ℚ × ℚ × ℚ × ℚ × ℚ :=
  (3/2 - 9/2, 9/2 - 3/2, 1 - 1, -5/12 - (-17/12), -9/4 - (-9/4), -8 - (-8))

/-- F_τ - F_t coefficient differences.
    (c_yt², c_yb², c_yτ², c_g₁², c_g₂², c_g₃²) -/
def diffCoeffs_τt : ℚ × ℚ × ℚ × ℚ × ℚ × ℚ :=
  (3 - 9/2, 3 - 3/2, 5/2 - 1, -15/4 - (-17/12), -9/4 - (-9/4), 0 - (-8))

/-! ## Verified coefficient differences -/

theorem diffCoeffs_bt_val : diffCoeffs_bt = (-3, 3, 0, 1, 0, 0) := by
  unfold diffCoeffs_bt; norm_num

theorem diffCoeffs_τt_val : diffCoeffs_τt = (-3/2, 3/2, 3/2, -28/12, 0, 8) := by
  unfold diffCoeffs_τt; norm_num

/-! ## Key structural observation

The y_t² coefficient in both (F_b - F_t) and (F_τ - F_t) is NEGATIVE.
When the top Yukawa dominates (y_t >> y_b, y_τ, which is the observed SM
hierarchy), the difference F_f - F_t is dominated by the negative y_t² term.
This means ṙ_f < 0: ratios decrease under RG flow toward the IR.

The mass hierarchy is PRESERVED by the RG flow, not GENERATED by it.
This is a structural property of the polynomial coefficients — it holds
at any finite step count and does not require any limit or omniscience.
-/

/-- The y_t² coefficient in F_b - F_t is negative. -/
theorem top_coeff_diff_bt_neg : diffCoeffs_bt.1 < 0 := by
  unfold diffCoeffs_bt; norm_num

/-- The y_t² coefficient in F_τ - F_t is negative. -/
theorem top_coeff_diff_τt_neg : diffCoeffs_τt.1 < 0 := by
  unfold diffCoeffs_τt; norm_num
