#!/usr/bin/env python3
"""
Paper 106 — CRM Audit of the Regular Holonomic Riemann-Hilbert Correspondence
Asymmetric Offloading: Python CAS → Lean 4 Verification

Test Case: The Gauss hypergeometric equation ₂F₁(a,b;c;z) on ℙ¹ \ {0,1,∞}

Parameters: a = 1/4, b = 1/3, c = 2/3 (chosen so all exponent differences
are non-integer, and Kummer connection matrices have well-defined
Gamma-ratio entries with no poles).

This script computes:
  1. The Picard-Fuchs ODE coefficients (BISH — polynomial arithmetic)
  2. Indicial polynomials at z = 0, 1, ∞ (BISH — rational root extraction)
  3. Local monodromy eigenvalues at each singularity (BISH — exp(2πi·exponent))
  4. Exponent differences and non-resonance (BISH — rational integer test)
  5. Fuchs relation (BISH — rational sum)
  6. Kummer connection matrix entries as Gamma-function ratios (CLASS boundary)
  7. Deligne canonical extension eigenvalue shifts (LPO boundary)

Output: P106_RiemannHilbert/RHData.lean with all verifiable constants.

Author: Paul Chun-Kit Lee (NYU)
"""

from sympy import (
    Rational, Poly, Matrix, Symbol, pi, I, exp, gamma, simplify
)


def gauss_hypergeometric_ode(a, b, c):
    """Return coefficients of z(1-z)y'' + [c-(a+b+1)z]y' - ab·y = 0."""
    z = Symbol('z')
    p2 = Poly(z * (1 - z), z, domain='QQ')
    p1 = Poly(c - (a + b + 1) * z, z, domain='QQ')
    p0 = Poly(-a * b, z, domain='QQ')
    return p2, p1, p0


def indicial_roots(a, b, c, point):
    """Indicial roots at a regular singular point (rational)."""
    if point == 0:
        return [Rational(0), 1 - c]
    elif point == 1:
        return [Rational(0), c - a - b]
    else:  # infinity
        return [a, b]


def deligne_fractional_part(r):
    """Fractional part in [0,1) for rational r. BISH for ℚ, LPO for ℂ."""
    r = Rational(r)
    frac = r - int(r)
    while frac < 0:
        frac += 1
    while frac >= 1:
        frac -= 1
    return Rational(frac)


def kummer_connection_matrix(a, b, c):
    """
    Kummer connection C₀₁ from z=0 basis to z=1 basis.
    Entries are Gamma-function ratios (CLASS boundary).
    """
    A = gamma(c) * gamma(c - a - b) / (gamma(c - a) * gamma(c - b))
    B = gamma(c) * gamma(a + b - c) / (gamma(a) * gamma(b))
    A2 = gamma(2 - c) * gamma(c - a - b) / (gamma(1 - a) * gamma(1 - b))
    B2 = gamma(2 - c) * gamma(a + b - c) / (gamma(a - c + 1) * gamma(b - c + 1))
    return Matrix([[A, B], [A2, B2]])


def emit_lean(a, b, c):
    """Emit RHData.lean."""
    r0 = indicial_roots(a, b, c, 0)
    r1 = indicial_roots(a, b, c, 1)
    rinf = indicial_roots(a, b, c, 'inf')

    d0 = [deligne_fractional_part(r) for r in r0]
    d1 = [deligne_fractional_part(r) for r in r1]
    dinf = [deligne_fractional_part(r) for r in rinf]

    C01 = kummer_connection_matrix(a, b, c)

    L = []
    L.append('import Mathlib.Tactic')
    L.append('')
    L.append('/-!')
    L.append('# Paper 106: RH Correspondence — CAS-Emitted Verification Data')
    L.append(f'# Test case: ₂F₁({a}, {b}; {c}; z) on ℙ¹ \\ {{0, 1, ∞}}')
    L.append('#')
    L.append('# Phase A (BISH): ODE coefficients, indicial roots, exponent differences,')
    L.append('#   non-resonance, Fuchs relation, Deligne shifts for rational params.')
    L.append('# Phase C/D (CLASS): Kummer connection coefficients (documentary).')
    L.append('#')
    L.append(f'# Generated by solve_rh_hypergeometric.py')
    L.append('-/')
    L.append('')
    L.append('namespace Paper106')
    L.append('')

    # Parameters
    L.append('-- ═══ ODE Parameters (BISH) ═══')
    L.append(f'def a_param : ℚ := {a}')
    L.append(f'def b_param : ℚ := {b}')
    L.append(f'def c_param : ℚ := {c}')
    L.append(f'def ab : ℚ := {a * b}')
    L.append(f'def apbp1 : ℚ := {a + b + 1}')
    L.append('')
    L.append('theorem ab_correct : a_param * b_param = ab := by norm_num [a_param, b_param, ab]')
    L.append('theorem apbp1_correct : a_param + b_param + 1 = apbp1 := by norm_num [a_param, b_param, apbp1]')
    L.append('')

    # Indicial roots
    L.append('-- ═══ Indicial Roots (BISH) ═══')
    for name, roots in [('zero', r0), ('one', r1), ('inf', rinf)]:
        L.append(f'def exp_{name}_1 : ℚ := {roots[0]}')
        L.append(f'def exp_{name}_2 : ℚ := {roots[1]}')
    L.append('')

    # Indicial equation verification
    L.append('-- Indicial equation at z=0: roots 0, 1-c')
    L.append('theorem indicial_zero_1 : exp_zero_1 = 0 := by norm_num [exp_zero_1]')
    L.append('theorem indicial_zero_2 : exp_zero_2 = 1 - c_param := by')
    L.append('  norm_num [exp_zero_2, c_param]')
    L.append('')
    L.append('-- Indicial equation at z=1: roots 0, c-a-b')
    L.append('theorem indicial_one_1 : exp_one_1 = 0 := by norm_num [exp_one_1]')
    L.append('theorem indicial_one_2 : exp_one_2 = c_param - a_param - b_param := by')
    L.append('  norm_num [exp_one_2, a_param, b_param, c_param]')
    L.append('')
    L.append('-- Indicial equation at z=∞: roots a, b')
    L.append('theorem indicial_inf_1 : exp_inf_1 = a_param := by norm_num [exp_inf_1, a_param]')
    L.append('theorem indicial_inf_2 : exp_inf_2 = b_param := by norm_num [exp_inf_2, b_param]')
    L.append('')

    # Exponent differences & non-resonance
    diffs = [
        ('zero', r0[1] - r0[0]),
        ('one', r1[1] - r1[0]),
        ('inf', rinf[1] - rinf[0])
    ]
    L.append('-- ═══ Exponent Differences & Non-Resonance (BISH) ═══')
    L.append('-- Resonance = difference ∈ ℤ. For ℚ-params: decidable. For ℂ-params: LPO.')
    for name, d in diffs:
        L.append(f'def diff_{name} : ℚ := {d}')
    L.append('')
    for name, d in diffs:
        L.append(f'theorem non_resonant_{name} : ∀ n : ℤ, (diff_{name} : ℚ) ≠ ↑n := by')
        L.append(f'  intro n; norm_num [diff_{name}]; omega')
    L.append('')

    # Fuchs relation
    total = sum(r0 + r1 + rinf)
    L.append('-- ═══ Fuchs Relation (BISH) ═══')
    L.append('-- Sum of all exponents = n-1 where n = number of singular points minus 1')
    L.append('-- For ℙ¹ with 3 singularities: sum = 3·1 - 2 = 1')
    L.append('theorem fuchs_relation :')
    L.append('    exp_zero_1 + exp_zero_2 + exp_one_1 + exp_one_2')
    L.append('    + exp_inf_1 + exp_inf_2 = 1 := by')
    L.append('  norm_num [exp_zero_1, exp_zero_2, exp_one_1, exp_one_2, exp_inf_1, exp_inf_2]')
    L.append('')

    # Deligne canonical extension
    L.append('-- ═══ Deligne Canonical Extension (LPO boundary) ═══')
    L.append('-- Shift exponents into [0,1): BISH for ℚ (integer floor), LPO for ℂ.')
    for name, shifted in [('zero', d0), ('one', d1), ('inf', dinf)]:
        L.append(f'def deligne_{name}_1 : ℚ := {shifted[0]}')
        L.append(f'def deligne_{name}_2 : ℚ := {shifted[1]}')
    L.append('')

    for name, shifted in [('zero', d0), ('one', d1), ('inf', dinf)]:
        for i, s in enumerate(shifted):
            L.append(f'theorem deligne_{name}_{i+1}_in_strip : 0 ≤ deligne_{name}_{i+1} ∧ deligne_{name}_{i+1} < 1 := by')
            L.append(f'  constructor <;> norm_num [deligne_{name}_{i+1}]')
    L.append('')

    # Connection matrix (documentary)
    L.append('-- ═══ Kummer Connection Matrix (CLASS — documentary) ═══')
    L.append('-- Entries are Gamma-function ratios. Exact evaluation requires')
    L.append('-- archimedean limits — the AOT obstruction (Paper 98, Thm 5.1).')
    L.append('-- Lean records symbolic forms; numerical values for reference only.')
    L.append('')
    for i in range(2):
        for j in range(2):
            val = C01[i, j]
            num_val = complex(val.evalf())
            L.append(f'-- C₀₁[{i},{j}] = {val}')
            L.append(f'--         ≈ {num_val.real:.10f} + {num_val.imag:.10f}·i')
    det_val = complex(simplify(C01.det()).evalf())
    L.append(f'-- det(C₀₁) ≈ {det_val.real:.10f} + {det_val.imag:.10f}·i')
    L.append('')

    L.append('end Paper106')
    return '\n'.join(L)


def main():
    a, b, c = Rational(1, 4), Rational(1, 3), Rational(2, 3)

    print(f"═══ Paper 106: CRM Audit of RH Correspondence ═══")
    print(f"Test case: ₂F₁({a}, {b}; {c}; z)")
    print()

    # ODE
    p2, p1, p0 = gauss_hypergeometric_ode(a, b, c)
    print(f"ODE: ({p2.as_expr()})y'' + ({p1.as_expr()})y' + ({p0.as_expr()})y = 0")

    # Indicial data
    for pt_name, pt in [('z=0', 0), ('z=1', 1), ('z=∞', 'inf')]:
        roots = indicial_roots(a, b, c, pt)
        deligne = [deligne_fractional_part(r) for r in roots]
        print(f"  {pt_name}: roots {roots[0]}, {roots[1]} → Deligne {deligne[0]}, {deligne[1]}")

    # Fuchs
    all_r = indicial_roots(a, b, c, 0) + indicial_roots(a, b, c, 1) + indicial_roots(a, b, c, 'inf')
    print(f"  Fuchs sum = {sum(all_r)}")

    # Connection matrix
    C01 = kummer_connection_matrix(a, b, c)
    print(f"  det(C₀₁) = {simplify(C01.det())}")

    # Emit
    lean_code = emit_lean(a, b, c)
    out = 'P106_RiemannHilbert/RHData.lean'
    with open(out, 'w') as f:
        f.write(lean_code)
    print(f"\nEmitted {out} ({len(lean_code.splitlines())} lines)")


if __name__ == '__main__':
    main()
