/-
  Paper 56 — Module 2: WeilLattice
  Exotic Weil Class Self-Intersection on CM Abelian Fourfolds

  Defines the exotic Weil lattice structure and dimension.
  Axiomatizes Milne's dimension result and Anderson's non-Lefschetz theorem.

  Sorry budget: 2 principled
    - milne_weil_dim (Milne 1999, Lemma 1.3)
    - exotic_not_lefschetz (Anderson 1993; Milne 1999, §1)

  Paul C.-K. Lee, February 2026
-/
import Papers.P56_ExoticWeilSelfInt.NumberFieldData

/-! # Exotic Weil Lattice

For a Weil-type CM abelian fourfold X = A × B:
- A: CM abelian threefold with CM signature (1,2) over K
- B: CM elliptic curve with signature (1,0) over K
- W(A,B) ⊂ H⁴(X, Q) is the space of exotic Weil classes

The exotic classes are Hodge type (2,2), primitive, and NOT in the
Lefschetz ring. Their Q-dimension is 2 (= 1 over K × [K:Q] = 2).
-/

-- ============================================================
-- Abstract types
-- ============================================================

/-- A quadratic imaginary field K = Q(√-d). -/
axiom QuadImagField : Type

/-- The degree [K:Q] = 2. -/
axiom QuadImagField.degree : QuadImagField → ℕ

/-- Every quadratic imaginary field has degree 2. -/
axiom QuadImagField.degree_eq : ∀ (K : QuadImagField), K.degree = 2

/-- A CM abelian threefold with CM by O_E, signature (1,2) over K. -/
axiom CMThreefold : QuadImagField → Type

/-- A CM elliptic curve with CM by O_K, signature (1,0). -/
axiom CMEllipticCurve : QuadImagField → Type

/-- The Weil-type abelian fourfold X = A × B. -/
structure WeilTypeFourfold (K : QuadImagField) where
  threefold : CMThreefold K
  elliptic : CMEllipticCurve K

/-- The exotic Weil space W(A,B) ⊂ H⁴(X, Q). -/
axiom ExoticWeilSpace : ∀ {K : QuadImagField}, WeilTypeFourfold K → Type

/-- Dimension of the exotic Weil space over K. -/
axiom dim_K_exotic : ∀ {K : QuadImagField}, WeilTypeFourfold K → ℕ

/-- Dimension of the exotic Weil space over Q. -/
axiom dim_Q_exotic : ∀ {K : QuadImagField}, WeilTypeFourfold K → ℕ

/-- The Lefschetz ring L(X): Q-subalgebra of cohomology generated by divisors. -/
axiom InLefschetzRing : ∀ {K : QuadImagField} (X : WeilTypeFourfold K),
  ExoticWeilSpace X → Prop

-- ============================================================
-- Principled axioms (sorry budget: 2)
-- ============================================================

/-- **Principled axiom: Milne's dimension result.**
The exotic Weil space has K-dimension 1.

Reference: Milne, "Lefschetz classes on abelian varieties",
Duke Math. J. 96 (1999), 639–675, Lemma 1.3. -/
axiom milne_weil_dim :
  ∀ (K : QuadImagField) (X : WeilTypeFourfold K),
    dim_K_exotic X = 1

/-- **Principled axiom: Exotic classes are NOT in the Lefschetz ring.**
Anderson (1993) showed that exotic Weil classes on abelian fourfolds
of Weil type lie outside the Q-subalgebra generated by divisors.

Reference: Anderson (1993), reported in Wei (2014);
Milne, Duke Math. J. 96 (1999), §1. -/
axiom exotic_not_lefschetz :
  ∀ (K : QuadImagField) (X : WeilTypeFourfold K)
    (w : ExoticWeilSpace X),
    ¬InLefschetzRing X w

-- ============================================================
-- Derived: Q-dimension = 2
-- ============================================================

/-- Scalar extension: dim_Q = dim_K × [K:Q]. -/
axiom dim_scalar_extension :
  ∀ (K : QuadImagField) (X : WeilTypeFourfold K),
    dim_Q_exotic X = dim_K_exotic X * K.degree

/-- **The Q-dimension of the exotic Weil space is 2.** -/
theorem weil_dim_Q (K : QuadImagField) (X : WeilTypeFourfold K) :
    dim_Q_exotic X = 2 := by
  rw [dim_scalar_extension]
  rw [milne_weil_dim, QuadImagField.degree_eq]
