/-
  CRM Paper 94: The Normal Function Squeeze — CAS-emitted data
  ====================================================
  Auto-generated by solve_mirror_quintic.py

  Verifies the Picard-Fuchs operator for the Mirror Quintic CY3
  in standard derivative form, and the conifold singular locus.

  The Mirror Quintic PF equation in theta-form:
    L_θ = θ⁴ - 5z·(5θ+1)(5θ+2)(5θ+3)(5θ+4)

  Converted to standard form L = Σ P_k(z) D^k via Stirling numbers.

  Stirling numbers of the second kind S(n,k):
    θ^n = Σ_{k=0}^{n} S(n,k) z^k D^k
    S(1,1)=1, S(2,1)=1, S(2,2)=1, S(3,1)=1, S(3,2)=3, S(3,3)=1
    S(4,1)=1, S(4,2)=7, S(4,3)=6, S(4,4)=1
-/
import Mathlib.Tactic.Ring
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.Linarith

-- §1. Picard-Fuchs coefficients in standard derivative form
-- L = P₄(z)D⁴ + P₃(z)D³ + P₂(z)D² + P₁(z)D + P₀(z)
-- Computed via Stirling expansion of the theta-form operator.

/-- Coefficient of D⁰ in the standard-form PF operator -/
noncomputable def pf_P0 (z : ℚ) : ℚ := -120 * z

/-- Coefficient of D¹ in the standard-form PF operator -/
noncomputable def pf_P1 (z : ℚ) : ℚ := -15000 * z ^ 2 + z

/-- Coefficient of D² in the standard-form PF operator -/
noncomputable def pf_P2 (z : ℚ) : ℚ := -45000 * z ^ 3 + 7 * z ^ 2

/-- Coefficient of D³ in the standard-form PF operator -/
noncomputable def pf_P3 (z : ℚ) : ℚ := -25000 * z ^ 4 + 6 * z ^ 3

/-- Coefficient of D⁴ (leading coefficient) in the standard-form PF operator -/
noncomputable def pf_P4 (z : ℚ) : ℚ := -3125 * z ^ 5 + z ^ 4

-- §2. RHS product expansion identity
-- (5θ+1)(5θ+2)(5θ+3)(5θ+4) = 625θ⁴ + 1250θ³ + 875θ² + 250θ + 24
-- Verified by expanding the product of four linear factors over ℤ[θ]

theorem rhs_product_expand (t : ℤ) :
    (5 * t + 1) * (5 * t + 2) * (5 * t + 3) * (5 * t + 4) =
    625 * t ^ 4 + 1250 * t ^ 3 + 875 * t ^ 2 + 250 * t + 24 := by ring

-- §3. Leading coefficient factorization (singular locus)

theorem pf_leading_factorization (z : ℚ) :
    pf_P4 z = z ^ 4 * (1 - 3125 * z) := by
  unfold pf_P4; ring

-- §4. The Conifold Discriminant

def conifold_discriminant (z : ℚ) : ℚ := 1 - 3125 * z

theorem conifold_singularity_exact :
    conifold_discriminant (1 / 3125) = 0 := by
  unfold conifold_discriminant; norm_num

theorem mum_point_singular :
    pf_P4 0 = 0 := by
  unfold pf_P4; ring

-- The leading coefficient vanishes at z = 0 (MUM point) and z = 1/3125 (conifold)
-- These are the two finite regular singular points of the PF equation
-- z = ∞ is the third (Gepner/orbifold point)

-- §5. Weyl algebra expansion verification
-- For each D^k, the sum of Stirling contributions from all θ^n terms equals P_k(z).
--
-- L_θ = θ⁴ - 5z·(5θ+1)(5θ+2)(5θ+3)(5θ+4)
--     = (1-3125z)·θ⁴ - 6250z·θ³ - 4375z·θ² - 1250z·θ - 120z
--
-- θ^n = Σ_k S(n,k) z^k D^k, so each (c_n · θ^n) contributes c_n · S(n,k) · z^k to D^k.
-- We verify the total at each D^k matches the standard-form coefficient P_k(z).

-- D⁴: (1-3125z)·S(4,4)·z⁴ = (1-3125z)·1·z⁴
theorem weyl_D4_coeff (z : ℚ) :
    (1 - 3125 * z) * 1 * z ^ 4 = pf_P4 z := by
  unfold pf_P4; ring

-- D³: (1-3125z)·S(4,3)·z³ + (-6250z)·S(3,3)·z³
theorem weyl_D3_coeff (z : ℚ) :
    (1 - 3125 * z) * 6 * z ^ 3 + (-6250 * z) * 1 * z ^ 3 = pf_P3 z := by
  unfold pf_P3; ring

-- D²: (1-3125z)·S(4,2)·z² + (-6250z)·S(3,2)·z² + (-4375z)·S(2,2)·z²
theorem weyl_D2_coeff (z : ℚ) :
    (1 - 3125 * z) * 7 * z ^ 2 + (-6250 * z) * 3 * z ^ 2 +
    (-4375 * z) * 1 * z ^ 2 = pf_P2 z := by
  unfold pf_P2; ring

-- D¹: contributions from θ⁴(S(4,1)=1), θ³(S(3,1)=1), θ²(S(2,1)=1), θ¹(S(1,1)=1)
theorem weyl_D1_coeff (z : ℚ) :
    (1 - 3125 * z) * 1 * z + (-6250 * z) * 1 * z +
    (-4375 * z) * 1 * z + (-1250 * z) * 1 * z = pf_P1 z := by
  unfold pf_P1; ring

-- D⁰: only the constant term -120z contributes (θ⁰ = identity)
theorem weyl_D0_coeff (z : ℚ) :
    -120 * z = pf_P0 z := by
  unfold pf_P0; ring

-- §6. Indicial exponents at MUM point (z = 0)
-- For the theta-form, the indicial equation at z=0 is θ⁴ = 0 (since the 5z·(...) vanishes).
-- All four roots are ρ = 0: maximally unipotent monodromy (MUM).

theorem mum_indicial_vanishes : (0 : ℤ) ^ 4 = 0 := by norm_num

-- §7. Indicial exponents at Conifold (z = 1/3125)
-- The indicial exponents are {0, 1, 1, 2}.
-- The repeated exponent 1 indicates a rank-1 logarithmic singularity.
-- Physically: the vanishing 3-cycle S³ that becomes the massless D-brane.

-- Indicial polynomial: ρ(ρ-1)²(ρ-2) = ρ⁴ - 4ρ³ + 5ρ² - 2ρ
theorem conifold_indicial_poly (r : ℤ) :
    r * (r - 1) * (r - 1) * (r - 2) = r ^ 4 - 4 * r ^ 3 + 5 * r ^ 2 - 2 * r := by ring

-- Roots: 0, 1 (double), 2
theorem conifold_indicial_root0 : (0 : ℤ) * (0 - 1) * (0 - 1) * (0 - 2) = 0 := by norm_num
theorem conifold_indicial_root1 : (1 : ℤ) * (1 - 1) * (1 - 1) * (1 - 2) = 0 := by norm_num
theorem conifold_indicial_root2 : (2 : ℤ) * (2 - 1) * (2 - 1) * (2 - 2) = 0 := by norm_num

-- §8. Dwork pencil parameter identity
-- The Dwork family: x₁⁵ + x₂⁵ + x₃⁵ + x₄⁵ + x₅⁵ = 5ψ·x₁x₂x₃x₄x₅
-- Mirror map parameter: z = 1/(5ψ)⁵
-- Conifold at z = 1/3125 corresponds to ψ = 1 (where 5⁵ = 3125)

theorem dwork_parameter_identity : (5 : ℤ) ^ 5 = 3125 := by norm_num

-- §9. Betti number rigidity
-- Every smooth quintic threefold in ℙ⁴ has h²·²(X) = 1.
-- The Betti numbers are topological invariants: b₀=1, b₂=1, b₃=204, b₄=1, b₆=1.
-- Extra H²·² classes CANNOT appear by deformation — this requires singular transitions.
-- Correction of a common misconception: the "new" Hodge classes at special points
-- arise from conifold transitions (topology change), not smooth deformation.

-- h^{1,1} = 1, h^{2,2} = 1 for ALL smooth quintic 3-folds
-- The single H^{2,2} class is the hyperplane-squared class H² ∈ H⁴(X, ℤ)
-- The Hodge Conjecture for H^{2,2} of a smooth quintic is therefore trivially true:
-- every H^{2,2} class is a rational multiple of H².

-- The INTERESTING Hodge problem for CY3 is in H³ (the middle cohomology).
-- dim H³ = b₃ = 204, split as h^{2,1} = 101 complex structure deformations
-- and h^{1,2} = 101 (conjugate). The Picard-Fuchs equation governs periods of H³.
