#!/usr/bin/env python3
"""
solve_flat_sections.py — Paper 81: Algebraic Flat Sections and the Theorem of the Fixed Part

Computes the 4×4 tensor Gauss–Manin connection on H¹⊗H¹ for the Legendre
elliptic family y² = x(x-1)(x-t), verifies the symplectic form W = (0,1,-1,0)
is a constant flat section, and emits FlatData.lean.

Base connection (from Paper 80):
  M_num = [[t, -1], [t, -t]]   denominator 2Δ where Δ = t(1-t)

Tensor connection: M_tens = M⊗I₂ + I₂⊗M  (Kronecker sum)
Numerator matrix:  N(t) = M_num⊗I₂ + I₂⊗M_num

Author: Paul Chun-Kit Lee (NYU) with Claude Code
"""

from sympy import Matrix, symbols, simplify, zeros, eye, pprint, Rational
import textwrap, os

t = symbols('t')

# ── Section 1: Base connection matrix (Paper 80) ──────────────────────────

M = Matrix([
    [t, -1],
    [t, -t]
])

print("=== Base Connection Matrix (numerator) ===")
pprint(M)
print(f"Trace: {simplify(M.trace())}")
assert simplify(M.trace()) == 0, "Base matrix must be traceless"

# ── Section 2: Kronecker sum → 4×4 tensor connection ─────────────────────

I2 = eye(2)
M_kron_I = Matrix(4, 4, lambda i, j:
    M[i // 2, j // 2] * I2[i % 2, j % 2])
I_kron_M = Matrix(4, 4, lambda i, j:
    I2[i // 2, j // 2] * M[i % 2, j % 2])

N = M_kron_I + I_kron_M

print("\n=== Tensor Connection Numerator N(t) = M⊗I + I⊗M ===")
pprint(N)

# ── Section 3: Structural properties ─────────────────────────────────────

print("\n=== Structural Properties ===")

# Trace
tr = simplify(N.trace())
print(f"Trace(N) = {tr}")
assert tr == 0, "Tensor connection must be traceless"

# Row equality: rows 1 and 2
for j in range(4):
    assert simplify(N[1, j] - N[2, j]) == 0, f"Row 1 != Row 2 at col {j}"
print("Row 1 = Row 2: CONFIRMED")

# Column equality: cols 1 and 2
for i in range(4):
    assert simplify(N[i, 1] - N[i, 2]) == 0, f"Col 1 != Col 2 at row {i}"
print("Col 1 = Col 2: CONFIRMED")

# ── Section 4: Flat section W = (0, 1, -1, 0) ────────────────────────────

W = Matrix([0, 1, -1, 0])
NW = N * W

print("\n=== Flat Section Verification: N(t) · W ===")
for i in range(4):
    val = simplify(NW[i])
    print(f"  Row {i}: {val}")
    assert val == 0, f"Flat section failed at row {i}"
print("W = (0,1,-1,0) is a CONSTANT FLAT SECTION: CONFIRMED")

# ── Section 5: Non-flatness of S = (0, 1, 1, 0) ─────────────────────────

S = Matrix([0, 1, 1, 0])
NS = N * S

print("\n=== Non-Flatness Verification: N(t) · S ===")
for i in range(4):
    val = simplify(NS[i])
    print(f"  Row {i}: {val}")
print(f"N·S = ({NS[0]}, {NS[1]}, {NS[2]}, {NS[3]}) ≠ 0: CONFIRMED")
assert simplify(NS[0]) != 0, "S should NOT be flat"

# ── Section 6: Full kernel over Q(t) ─────────────────────────────────────

print("\n=== Kernel Analysis over Q(t) ===")
# SymPy nullspace gives (0,-1,1,0) and (1/t, 2, 0, 1).
# Clear denominator: K(t) = (1, 2t, 0, t)
K = Matrix([1, 2*t, 0, t])
NK = N * K

for i in range(4):
    val = simplify(NK[i])
    print(f"  N·K row {i}: {val}")
    assert val == 0, f"K(t) not in kernel at row {i}"
print("K(t) = (1, 2t, 0, t) is in ker N(t): CONFIRMED")
print(f"Kernel over Q(t): 2-dimensional, spanned by W and K(t)")

# ── Section 7: Constant kernel restriction ────────────────────────────────

print("\n=== Constant Kernel Analysis ===")
print("General kernel vector: a·K(t) + b·W = (a, 2at+b, -b, at)")
print("  Entry 3 = at is constant iff a = 0")
print("  => constant kernel = span{W}, dimension 1")
print("This is the algebraic Theorem of the Fixed Part.")

# ── Section 8: Emit FlatData.lean ─────────────────────────────────────────

print("\n=== Emitting FlatData.lean ===")

# Build the entry names and values
entries = []
for i in range(4):
    for j in range(4):
        val = N[i, j]
        entries.append((i, j, val))

lean_code = textwrap.dedent("""\
import Mathlib

/-!
# FlatData.lean — Paper 81: Algebraic Flat Sections

Auto-generated by `solve_flat_sections.py`.

## Target
Legendre elliptic family y² = x(x-1)(x-t).
Tensor Gauss–Manin connection on H¹ ⊗ H¹.

## Base connection (Paper 80)
M_num = [[t, -1], [t, -t]], denominator 2Δ where Δ = t(1-t).

## Tensor connection
N(t) = M⊗I₂ + I₂⊗M  (Kronecker sum of numerator matrices).

N(t) = [[2t, -1, -1,  0],
        [ t,  0,  0, -1],
        [ t,  0,  0, -1],
        [ 0,  t,  t, -2t]]

## Key results
- W = (0,1,-1,0) is the unique constant flat section (symplectic form).
- S = (0,1,1,0) is NOT flat (symmetric form).
- Full kernel over Q(t) is 2-dimensional: span{W, K(t)} where K(t) = (1,2t,0,t).
- Constant kernel = span{W}, 1-dimensional: the algebraic Theorem of the Fixed Part.
-/

namespace P81_FlatSections

/-! ## §1. Base connection matrix entries (from Paper 80) -/

/-- Base GM connection numerator M₁₁(t) = t -/
def base_M11 (t : ℚ) : ℚ := t

/-- Base GM connection numerator M₁₂ = -1 -/
def base_M12 : ℚ := -1

/-- Base GM connection numerator M₂₁(t) = t -/
def base_M21 (t : ℚ) : ℚ := t

/-- Base GM connection numerator M₂₂(t) = -t -/
def base_M22 (t : ℚ) : ℚ := -t

/-- Identity 1: Base connection is traceless -/
theorem base_traceless (t : ℚ) :
    base_M11 t + base_M22 t = 0 := by
  simp only [base_M11, base_M22]; ring

/-! ## §2. Tensor connection matrix entries (Kronecker sum) -/

/-- Tensor connection numerator N₀₀(t) = M₁₁ + M₁₁ = 2t -/
def N00 (t : ℚ) : ℚ := 2 * t

/-- Tensor connection numerator N₀₁ = M₁₂ + 0 = -1 -/
def N01 : ℚ := -1

/-- Tensor connection numerator N₀₂ = 0 + M₁₂ = -1 -/
def N02 : ℚ := -1

/-- Tensor connection numerator N₀₃ = 0 -/
def N03 : ℚ := 0

/-- Tensor connection numerator N₁₀(t) = M₂₁ + 0 = t -/
def N10 (t : ℚ) : ℚ := t

/-- Tensor connection numerator N₁₁ = M₂₂ + M₁₁ = 0 -/
def N11 : ℚ := 0

/-- Tensor connection numerator N₁₂ = 0 -/
def N12 : ℚ := 0

/-- Tensor connection numerator N₁₃ = M₁₂ = -1 -/
def N13 : ℚ := -1

/-- Tensor connection numerator N₂₀(t) = M₂₁ = t -/
def N20 (t : ℚ) : ℚ := t

/-- Tensor connection numerator N₂₁ = 0 -/
def N21 : ℚ := 0

/-- Tensor connection numerator N₂₂ = 0 -/
def N22 : ℚ := 0

/-- Tensor connection numerator N₂₃ = M₂₂ + M₁₂ = -1 -/
def N23 : ℚ := -1

/-- Tensor connection numerator N₃₀ = 0 -/
def N30 : ℚ := 0

/-- Tensor connection numerator N₃₁(t) = M₂₁ = t -/
def N31 (t : ℚ) : ℚ := t

/-- Tensor connection numerator N₃₂(t) = M₂₁ = t -/
def N32 (t : ℚ) : ℚ := t

/-- Tensor connection numerator N₃₃(t) = M₂₂ + M₂₂ = -2t -/
def N33 (t : ℚ) : ℚ := -2 * t

/-! ## §3. Kronecker sum verification

Each N_ij = (M⊗I)_ij + (I⊗M)_ij.  Key entries verified. -/

/-- Identity 2: N₀₀ = M₁₁·I₁₁ + I₁₁·M₁₁ = t + t -/
theorem N00_kronecker (t : ℚ) :
    N00 t = base_M11 t * 1 + 1 * base_M11 t := by
  simp only [N00, base_M11]; ring

/-- Identity 3: N₁₁ = M₁₁·I₂₂ + I₁₁·M₂₂ = t + (-t) -/
theorem N11_kronecker (t : ℚ) :
    (N11 : ℚ) = base_M11 t * 1 + 1 * base_M22 t := by
  simp only [N11, base_M11, base_M22]; ring

/-- Identity 4: N₃₃ = M₂₂·I₂₂ + I₂₂·M₂₂ = -t + (-t) -/
theorem N33_kronecker (t : ℚ) :
    N33 t = base_M22 t * 1 + 1 * base_M22 t := by
  simp only [N33, base_M22]; ring

/-! ## §4. Structural properties -/

/-- Identity 5: Row 1 = Row 2, component 0 -/
theorem row_eq_10_20 (t : ℚ) : N10 t = N20 t := rfl

/-- Identity 6: Row 1 = Row 2, component 1 -/
theorem row_eq_11_21 : N11 = N21 := rfl

/-- Identity 7: Row 1 = Row 2, component 2 -/
theorem row_eq_12_22 : N12 = N22 := rfl

/-- Identity 8: Row 1 = Row 2, component 3 -/
theorem row_eq_13_23 : N13 = N23 := rfl

/-- Identity 9: Column 1 = Column 2, component 0 -/
theorem col_eq_01_02 : N01 = N02 := rfl

/-- Identity 10: Column 1 = Column 2, component 1 -/
theorem col_eq_11_12 : N11 = N12 := rfl

/-- Identity 11: Column 1 = Column 2, component 2 -/
theorem col_eq_21_22 : N21 = N22 := rfl

/-- Identity 12: Column 1 = Column 2, component 3 -/
theorem col_eq_31_32 (t : ℚ) : N31 t = N32 t := rfl

/-- Identity 13: Tensor connection is traceless -/
theorem tensor_traceless (t : ℚ) :
    N00 t + (N11 : ℚ) + (N22 : ℚ) + N33 t = 0 := by
  simp only [N00, N11, N22, N33]; ring

/-! ## §5. Flat section W = (0, 1, -1, 0): the symplectic form

The antisymmetric intersection form on H¹ is a constant flat section
of the tensor Gauss–Manin connection.  This means the intersection
pairing is preserved by parallel transport — verified by polynomial
algebra, bypassing topological monodromy.
-/

/-- Identity 14: N(t)·W row 0 = 0 -/
theorem flat_W_row0 (t : ℚ) :
    N00 t * 0 + N01 * 1 + N02 * (-1) + N03 * 0 = 0 := by
  simp only [N00, N01, N02, N03]; ring

/-- Identity 15: N(t)·W row 1 = 0 -/
theorem flat_W_row1 (t : ℚ) :
    N10 t * 0 + N11 * 1 + N12 * (-1) + N13 * 0 = 0 := by
  simp only [N10, N11, N12, N13]; ring

/-- Identity 16: N(t)·W row 2 = 0 -/
theorem flat_W_row2 (t : ℚ) :
    N20 t * 0 + N21 * 1 + N22 * (-1) + N23 * 0 = 0 := by
  simp only [N20, N21, N22, N23]; ring

/-- Identity 17: N(t)·W row 3 = 0 -/
theorem flat_W_row3 (t : ℚ) :
    N30 * 0 + N31 t * 1 + N32 t * (-1) + N33 t * 0 = 0 := by
  simp only [N30, N31, N32, N33]; ring

/-! ## §6. Non-flatness of S = (0, 1, 1, 0): the symmetric form

The symmetric bilinear form is NOT preserved by the Gauss–Manin
connection.  N(t)·S = (-2, 0, 0, 2t).
-/

/-- Identity 18: N(t)·S row 0 = -2 (constant, nonzero) -/
theorem nonflat_S_row0 (t : ℚ) :
    N00 t * 0 + N01 * 1 + N02 * 1 + N03 * 0 = -2 := by
  simp only [N00, N01, N02, N03]; ring

/-- Identity 19: N(t)·S row 3 = 2t -/
theorem nonflat_S_row3 (t : ℚ) :
    N30 * 0 + N31 t * 1 + N32 t * 1 + N33 t * 0 = 2 * t := by
  simp only [N30, N31, N32, N33]; ring

/-- The first component is nonzero: S is not flat -/
theorem S_image_nonzero : (-2 : ℚ) ≠ 0 := by decide

/-! ## §7. Full kernel basis over Q(t)

K(t) = (1, 2t, 0, t) is the second kernel vector (denominator-cleared
from SymPy's (1/t, 2, 0, 1)).  Together with W, it spans ker N(t)
over Q(t).
-/

/-- Identity 20: N(t)·K row 0 = 0 -/
theorem kernel_K_row0 (t : ℚ) :
    N00 t * 1 + N01 * (2 * t) + N02 * 0 + N03 * t = 0 := by
  simp only [N00, N01, N02, N03]; ring

/-- Identity 21: N(t)·K row 1 = 0 -/
theorem kernel_K_row1 (t : ℚ) :
    N10 t * 1 + N11 * (2 * t) + N12 * 0 + N13 * t = 0 := by
  simp only [N10, N11, N12, N13]; ring

/-- Identity 22: N(t)·K row 2 = 0 -/
theorem kernel_K_row2 (t : ℚ) :
    N20 t * 1 + N21 * (2 * t) + N22 * 0 + N23 * t = 0 := by
  simp only [N20, N21, N22, N23]; ring

/-- Identity 23: N(t)·K row 3 = 0 -/
theorem kernel_K_row3 (t : ℚ) :
    N30 * 1 + N31 t * (2 * t) + N32 t * 0 + N33 t * t = 0 := by
  simp only [N30, N31, N32, N33]; ring

/-! ## §8. Constant kernel restriction

The general kernel vector is a·K(t) + b·W = (a, 2at+b, -b, at).
For this to be constant (t-independent), the 4th entry at must be
constant, which forces a = 0.  Then the vector reduces to b·W.

So the constant kernel = span{W}, 1-dimensional.
This is the algebraic Theorem of the Fixed Part.
-/

/-- Identity 24: If at is the same at t=0 and t=1, then a=0 -/
theorem constant_kernel_forces_a_zero (a : ℚ) (h : a * (0 : ℚ) = a * (1 : ℚ)) :
    a = 0 := by linarith

/-- Identity 25: A 2×2 minor of N is nonzero, confirming rank ≥ 2 -/
theorem rank_witness (t : ℚ) :
    N00 t * N33 t - N03 * N30 = -4 * t ^ 2 := by
  simp only [N00, N33, N03, N30]; ring

/-!
## Summary

25 identities verified over ℚ[t]:
- 1 base tracelessness
- 3 Kronecker sum verifications
- 8 row/column equality (4 + 4)
- 1 tensor tracelessness
- 4 flat section (W)
- 2 non-flatness (S) + 1 nonzero witness
- 4 full kernel (K)
- 1 constant kernel restriction

All proofs: `ring`, `rfl`, `decide`, or `linarith`.
All BISH — no Classical.choice in the mathematical content.
-/

end P81_FlatSections
""")

out_path = os.path.join(os.path.dirname(__file__),
                        "P81_FlatSections", "Papers", "P81_FlatSections", "FlatData.lean")
os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, 'w') as f:
    f.write(lean_code)

lines = lean_code.count('\n')
print(f"Wrote FlatData.lean: {lines} lines → {out_path}")
print("\n=== ALL CHECKS PASSED ===")
