/-
  Paper 18: Standard Model Yukawa RG — Ratio Beta Structural Theorem
  Part of the Constructive Calibration Programme

  THEOREM 3: In the top-dominant regime (y_t² >> y_b², y_τ², g_i²),
  the ratio betas ṙ_b and ṙ_τ are strictly negative, meaning the
  mass hierarchy is structurally preserved by RG flow.

  This is a BISH result: it depends only on the signs of rational
  coefficients in the polynomial beta functions. No limit, no
  omniscience, no completed infinite object is involved.

  The physical consequence: the SM fermion mass hierarchy (m_t >> m_b >> m_τ)
  cannot be GENERATED by infrared RG flow from generic UV initial conditions.
  It must be imposed as a UV boundary condition. This is Paper 18's central
  negative result, now formalized.
-/

import Papers.P18_YukawaRG.Defs

/-! ## The ratio beta function

For ratio r_f = y_f / y_t, the RG equation is:
  ṙ_f = r_f · (F_f - F_t)

where F_f - F_t = Δc₁·y_t² + Δc₂·y_b² + Δc₃·y_τ² + (gauge terms).

In the top-dominant regime, the y_t² term dominates. Since Δc₁ < 0
for both b/t and τ/t ratios (proved in Defs.lean), ṙ_f < 0.

We formalize this as: given y_t² sufficiently large relative to the
other couplings, the difference F_f - F_t is strictly negative.
-/

/-- The difference F_b - F_t evaluated at couplings (y_t², y_b², y_τ², g₁², g₂², g₃²).
    All arguments are squared couplings (non-negative). -/
noncomputable def rateBetaDiff_bt (yt2 yb2 yτ2 g12 g22 g32 : ℝ) : ℝ :=
  (-3) * yt2 + 3 * yb2 + 0 * yτ2 + 1 * g12 + 0 * g22 + 0 * g32

/-- The difference F_τ - F_t evaluated at couplings. -/
noncomputable def rateBetaDiff_τt (yt2 yb2 yτ2 g12 g22 g32 : ℝ) : ℝ :=
  (-3/2) * yt2 + (3/2) * yb2 + (3/2) * yτ2 + (-7/3) * g12 + 0 * g22 + 8 * g32

/-! ## Top-dominant regime: F_b - F_t < 0

When y_t² is large enough to dominate the positive terms, the ratio
beta difference is negative. This is a purely algebraic statement
about rational coefficients — BISH throughout.
-/

/-- In the top-dominant regime, F_b - F_t < 0.
    Specifically: if 3·y_t² > 3·y_b² + g₁² (the positive terms), then
    the ratio beta difference is strictly negative. -/
theorem rateBetaDiff_bt_neg_of_top_dominant
    (yt2 yb2 yτ2 g12 g22 g32 : ℝ)
    (_hyt2 : 0 < yt2)
    (_hyb2 : 0 ≤ yb2) (_hyτ2 : 0 ≤ yτ2)
    (_hg12 : 0 ≤ g12) (_hg22 : 0 ≤ g22) (_hg32 : 0 ≤ g32)
    (hdom : 3 * yb2 + g12 < 3 * yt2) :
    rateBetaDiff_bt yt2 yb2 yτ2 g12 g22 g32 < 0 := by
  unfold rateBetaDiff_bt
  linarith

/-- In the top-dominant regime, F_τ - F_t < 0.
    Specifically: if (3/2)·y_t² > (3/2)·y_b² + (3/2)·y_τ² + 8·g₃² (when g₁ contributes negatively).
    Note: the g₁² coefficient is -7/3 (negative), so it helps.
    Sufficient condition: (3/2)·y_t² > (3/2)·y_b² + (3/2)·y_τ² + 8·g₃². -/
theorem rateBetaDiff_τt_neg_of_top_dominant
    (yt2 yb2 yτ2 g12 g22 g32 : ℝ)
    (_hyt2 : 0 < yt2)
    (_hyb2 : 0 ≤ yb2) (_hyτ2 : 0 ≤ yτ2)
    (hg12 : 0 ≤ g12) (_hg22 : 0 ≤ g22) (_hg32 : 0 ≤ g32)
    (hdom : (3 : ℝ)/2 * yb2 + (3 : ℝ)/2 * yτ2 + 8 * g32 < (3 : ℝ)/2 * yt2) :
    rateBetaDiff_τt yt2 yb2 yτ2 g12 g22 g32 < 0 := by
  unfold rateBetaDiff_τt
  have hg12_neg : (-7/3 : ℝ) * g12 ≤ 0 := by nlinarith
  linarith

/-! ## Physical interpretation

These theorems formalize the structural explanation for Paper 18's negative result:

1. The SM beta functions are polynomial with rational coefficients (BISH data).
2. In the top-dominant regime (which IS the observed SM), ratio betas are negative.
3. Therefore mass ratios r_b = y_b/y_t and r_τ = y_τ/y_t DECREASE under
   forward (UV → IR) RG flow.
4. This means any initial hierarchy at the UV scale is AMPLIFIED by the flow,
   not generated.
5. The mass hierarchy must be imposed as a UV boundary condition — the IR RG
   cannot produce it from generic (democratic) initial conditions.

No omniscience principle is used. The argument is purely algebraic.
The #print axioms output should show no Classical.choice for these theorems.
-/

#print axioms rateBetaDiff_bt_neg_of_top_dominant
#print axioms rateBetaDiff_τt_neg_of_top_dominant
#print axioms diffCoeffs_bt_val
#print axioms diffCoeffs_τt_val
#print axioms top_coeff_diff_bt_neg
#print axioms top_coeff_diff_τt_neg
