/-
  ConjDData.lean — Auto-generated by solve_generic_weil.py
  Paper 79: Standard Conjecture D for Abelian Fourfolds of Weil Type Is Constructively Decidable

  Target: Generic abelian fourfold with K = Q(i) action.
  Exotic Weil subspace: 2-dimensional, spanned by Re(w) and Im(w)
  where w = v1 ^ v2 ^ v3 ^ v4, v_k = e_k - I*f_k.

  Gram matrix: [[8, 0], [0, 8]]
  Determinant: 64
  Definiteness: positive

  DO NOT EDIT — regenerate via: python3 solve_generic_weil.py
-/

import Mathlib

/-- Dimension of the exotic Weil subspace. -/
def exoticDim : Nat := 2

/-- Gram matrix entry G(1,1) = <w_R, w_R>. -/
def gram_matrix_11 : ℤ := 8

/-- Gram matrix entry G(1,2) = G(2,1) = <w_R, w_I>. -/
def gram_matrix_12 : ℤ := 0

/-- Gram matrix entry G(2,2) = <w_I, w_I>. -/
def gram_matrix_22 : ℤ := 8

/-- Sylvester's criterion: the exotic Gram matrix is positive definite.
    First minor: G11 > 0.
    Second minor: G11 * G22 - G12^2 > 0. -/
theorem exotic_pairing_is_definite :
    (gram_matrix_11 > 0) ∧
    (gram_matrix_11 * gram_matrix_22 - gram_matrix_12 * gram_matrix_12 > 0) := by
  decide

/-- Leading principal minors for the CRM audit record. -/
def leadingPrincipalMinors : List ℤ := [8, 64]

theorem allMinorsPositive : (leadingPrincipalMinors.all (· > 0)) = true := by
  decide

