name: CI Nightly - Rho4 Pathology

on:
  schedule:
    # Run nightly at 2 AM UTC for Sprint 36 branch
    - cron: '0 2 * * *'
  push:
    branches: [ feat/rho4-pathology ]
  pull_request:
    branches: [ feat/rho4-pathology ]

env:
  LEAN_ABORT_ON_SORRY: 1
  BUILD_TIMEOUT_SECONDS: 90

jobs:
  rho4-pathology-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Lean
        uses: leanprover/lean-action@v1
        with:
          use-mathlib-cache: true
          build-args: "-K 400000"

      - name: Cache .lake
        uses: actions/cache@v3
        with:
          path: |
            ~/.lake
            .lake/build
          key: ${{ runner.os }}-lake-rho4-${{ hashFiles('lakefile.lean') }}

      - name: Build with timeout
        timeout-minutes: 2
        run: |
          echo "Building œÅ=4 pathology branch with timeout of $BUILD_TIMEOUT_SECONDS seconds..."
          time lake build
          echo "Build completed successfully"

      - name: Verify Sprint 36 progress
        run: |
          echo "Verifying Sprint 36 œÅ=4 pathology progress..."
          
          # Check for Sprint 36 design document
          if [ -f docs/sprint36-design.md ]; then
            echo "‚úÖ Sprint 36 design document found"
          else
            echo "‚ö†Ô∏è  Sprint 36 design document pending"
          fi
          
          # Check for œÅ=4 pathology scaffolding
          if [ -f Rho4Pathology.lean ] || [ -d Rho4Pathology/ ]; then
            echo "‚úÖ œÅ=4 pathology scaffolding found"
          else
            echo "‚ö†Ô∏è  œÅ=4 pathology scaffolding pending"
          fi
          
          # Verify existing hierarchy still works
          echo "Verifying existing œÅ-hierarchy preservation..."
          
          # Test œÅ=1 level
          echo 'import Gap2.Proofs
          #check Gap.Proofs.Gap_requires_WLPO' | lake env lean --stdin
          
          # Test œÅ=3 level  
          echo 'import AnalyticPathologies.Proofs
          #check AnalyticPathologies.SpectralGap_requires_ACœâ' | lake env lean --stdin
          
          echo "‚úÖ Existing hierarchy preserved during Sprint 36"

      - name: Verify no 'sorry' in core modules
        run: |
          if [ -f scripts/verify-no-sorry.sh ]; then
            bash scripts/verify-no-sorry.sh
          else
            echo "Warning: verify-no-sorry.sh not found"
          fi

      - name: Sprint 36 quality gates
        run: |
          echo "Sprint 36 Quality Gates Assessment:"
          echo "- Build time: $(echo 'Measured in build step above')"
          echo "- Sorry statements: $(grep -r 'sorry' --exclude-dir=.git --include='*.lean' . | wc -l || echo 0)"  
          echo "- Branch: feat/rho4-pathology"
          echo "- Target: œÅ=4 pathology (stronger DC principles)"
          echo ""
          echo "Ready for Math-Coder AI Sprint 36 development üöÄ"