name: CI-Witness
on: [push, pull_request]

env:
  LEAN_ABORT_ON_SORRY: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Lean
        uses: leanprover/lean-action@v1

      - name: Cache .lake
        uses: actions/cache@v3
        with:
          path: |
            ~/.lake
            .lake/build
          key: ${{ runner.os }}-lake-${{ hashFiles('lakefile.lean') }}

      - name: Build
        run: lake build

      - name: Sanity – no 'sorry'
        run: bash scripts/verify-no-sorry.sh

      - name: Verify core mathematical proofs
        run: |
          # Verify key theorems compile and type-check correctly
          echo "Verifying Foundation-Relativity core theorems..."
          
          # Test Gap₂ requires WLPO (ρ=1)
          echo 'import Gap2.Proofs
          #check Gap.Proofs.Gap_requires_WLPO' | lake env lean --stdin
          
          # Test AP_Fail₂ requires WLPO (ρ=1)  
          echo 'import APFunctor.Proofs
          #check APFail.Proofs.AP_requires_WLPO' | lake env lean --stdin
          
          # Test RNP_Fail₂ requires DC_ω (ρ=2)
          echo 'import RNPFunctor.Proofs
          #check RNPFunctor.RNP_requires_DCω' | lake env lean --stdin
          
          # Test RNP₃ requires DC_{ω+1} (ρ=2+)
          echo 'import RNPFunctor.Proofs3
          #check RNPFunctor.RNP_requires_DCω_plus' | lake env lean --stdin
          
          # Test SpectralGap requires AC_ω (ρ=3) - Milestone C
          echo 'import AnalyticPathologies.Proofs
          #check AnalyticPathologies.SpectralGap_requires_ACω' | lake env lean --stdin
          
          echo "✅ All Foundation-Relativity theorems verified!"
