name: CI
on: [push, pull_request]

env:
  LEAN_ABORT_ON_SORRY: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Lean 4.3.0
        uses: leanprover/lean-action@v1
        with:
          lean-version: "4.3.0"

      - name: Cache .lake
        uses: actions/cache@v3
        with:
          path: |
            ~/.lake
            .lake/build
          key: ${{ runner.os }}-lake-${{ hashFiles('lakefile.lean') }}

      - name: Build
        run: lake build

      - name: Sanity – no 'sorry'
        run: bash scripts/verify-no-sorry.sh

      - name: Unit tests
        run: |
          lake exe testFunctors
          lake exe testNonIdMorphisms
          lake exe WitnessTests
          lake exe AllPathologiesTests
          lake exe Gap2ProofTests
          lake exe APProofTests
          lake exe RNPProofTests
          lake exe RNP3ProofTests
          lake exe SpectralGapProofTests
