name: P3B Axiom Budget Guard

on:
  pull_request:
    paths:
      - "Papers/P3_2CatFramework/**"
      - ".ci/check_axioms.sh"
  push:
    branches: [ main ]

jobs:
  axiom-guard:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run axiom guard
        run: |
          chmod +x .ci/check_axioms.sh
          ./.ci/check_axioms.sh
        shell: bash