name: Paper 6 Heisenberg

on:
  push:
    paths:
      - "Papers/P6_Heisenberg/**"
      - "scripts/no_sorry_p6.sh"  
      - "lakefile.lean"
      - "lean-toolchain"
  pull_request:
    paths:
      - "Papers/P6_Heisenberg/**"
      - "scripts/no_sorry_p6.sh"
      - "lakefile.lean" 
      - "lean-toolchain"

jobs:
  heisenberg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache elan & Lake build  
        uses: actions/cache@v4
        with:
          path: |
            ~/.elan
            ~/.cache/elan
            .lake
            lake-packages
          key: p6-heisenberg-${{ runner.os }}-${{ hashFiles('lean-toolchain', 'lake-manifest.json', 'lakefile.lean') }}
          restore-keys: |
            p6-heisenberg-${{ runner.os }}-

      - name: Install elan (Lean toolchain manager)
        run: |
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Print toolchain versions
        run: |
          lean --version
          lake --version

      - name: Build Paper 6 Heisenberg target (mathlib-free)
        run: lake build Papers.P6_Heisenberg.Smoke

      - name: No-sorry guard (Paper 6) 
        run: ./scripts/no_sorry_p6.sh