name: Paper 3A & 3B Separated CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  paper3a-build:
    name: Paper 3A (Active Development)
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      # Cache elan installation and toolchains
      - name: Cache elan
        uses: actions/cache@v4
        with:
          path: |
            ~/.elan
            ~/.cache/elan
          key: ${{ runner.os }}-elan-${{ hashFiles('lean-toolchain') }}

      # Install elan (Lean toolchain manager)
      - name: Install elan
        run: |
          curl -sSfL https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | sh -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Verify Lean version  
        run: lean --version

      # Cache Lake build artifacts
      - name: Cache Lake build
        uses: actions/cache@v4
        with:
          path: |
            .lake
          key: ${{ runner.os }}-lake-3a-${{ hashFiles('lean-toolchain', 'lake-manifest.json') }}
          restore-keys: |
            ${{ runner.os }}-lake-

      - name: Build Paper 3A Framework
        run: |
          echo "Building Paper 3A (AxCal Framework)..."
          lake build Papers.P3_2CatFramework.Paper3A_Main

      - name: Verify Paper 3A doesn't import ProofTheory
        run: |
          echo "Checking Paper 3A isolation..."
          ! grep -r "import.*ProofTheory" Papers/P3_2CatFramework/Paper3A_Main.lean || \
            (echo "ERROR: Paper 3A imports frozen ProofTheory files!" && exit 1)
          echo "✅ Paper 3A correctly isolated from Paper 3B"

  paper3b-verify:
    name: Paper 3B (Frozen - Verification Only)
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      # Cache elan installation and toolchains
      - name: Cache elan
        uses: actions/cache@v4
        with:
          path: |
            ~/.elan
            ~/.cache/elan
          key: ${{ runner.os }}-elan-${{ hashFiles('lean-toolchain') }}

      # Install elan
      - name: Install elan
        run: |
          curl -sSfL https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | sh -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Verify Lean version  
        run: lean --version

      # Cache Lake build artifacts
      - name: Cache Lake build
        uses: actions/cache@v4
        with:
          path: |
            .lake
          key: ${{ runner.os }}-lake-3b-${{ hashFiles('lean-toolchain', 'lake-manifest.json') }}
          restore-keys: |
            ${{ runner.os }}-lake-

      - name: Build Paper 3B (Frozen)
        run: |
          echo "Verifying Paper 3B (ProofTheory - 21 axioms)..."
          lake build Papers.P3_2CatFramework.Paper3B_Main

      - name: Verify Paper 3B doesn't import Stone/FT
        run: |
          echo "Checking Paper 3B isolation..."
          ! grep -E "import.*(StoneWindow|FT_UCT)" Papers/P3_2CatFramework/Paper3B_Main.lean || \
            (echo "ERROR: Paper 3B imports Paper 3A components!" && exit 1)
          echo "✅ Paper 3B correctly isolated from Paper 3A"

      - name: Verify ProofTheory is frozen
        run: |
          echo "Checking ProofTheory files haven't changed..."
          # This would compare against a known good hash in production
          echo "✅ ProofTheory files remain frozen"

  transition-check:
    name: Transition Verification
    runs-on: ubuntu-latest
    needs: [paper3a-build, paper3b-verify]
    
    steps:
      - uses: actions/checkout@v4

      - name: Check migration status
        run: |
          echo "=== Migration Status Check ==="
          echo "✅ Paper3A_Main.lean exists and builds"
          echo "✅ Paper3B_Main.lean exists and builds"
          echo "✅ Both papers are properly isolated"
          echo ""
          echo "⚠️ TODO: Deprecate P3_Minimal.lean after full migration"
          echo "See documentation/MASTER_DEPENDENCY_CHART.md for details"