name: Paper 3C Nightly (Optional)

on:
  schedule:
    # Run at 3 AM UTC daily
    - cron: '0 3 * * *'
  workflow_dispatch:  # Allow manual trigger
  push:
    paths:
      - 'Papers/P3C_DCwAxis/**'
    branches:
      - main
      - 'paper3c-*'

jobs:
  build-3c-lite:
    name: Build Paper 3C (without mathlib)
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install elan
        run: |
          curl -sSf https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | sh -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      
      - name: Build Paper 3C Main
        run: |
          echo "Building Paper 3C (lite, no mathlib)..."
          lake build Papers.P3C_DCwAxis.Paper3C_Main
          echo "✅ Paper 3C lite build successful"
      
      - name: Build DCw_Skeleton
        run: |
          echo "Building DCw_Skeleton waypoints..."
          lake build Papers.P3C_DCwAxis.DCw_Skeleton || true
          echo "✅ DCw_Skeleton checked (sorries allowed)"
  
  build-3c-mathlib:
    name: Build Paper 3C with mathlib binding
    runs-on: ubuntu-latest
    continue-on-error: true  # Don't fail the workflow if mathlib build fails
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install elan
        run: |
          curl -sSf https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | sh -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      
      - name: Get mathlib cache
        run: |
          lake exe cache get || echo "Cache not available"
      
      - name: Build mathlib binding (optional)
        run: |
          echo "Attempting to build DCw_TopBinding with mathlib..."
          lake build Papers.P3C_DCwAxis.DCw_TopBinding || {
            echo "⚠️ Mathlib binding build failed (expected if mathlib not available)"
            echo "This is non-blocking for 3C development"
            exit 0
          }
          echo "✅ Mathlib binding build successful"
  
  check-3c-isolation:
    name: Verify 3C doesn't affect 3A
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Verify no 3A imports of 3C
        run: |
          echo "Checking that 3A doesn't import 3C..."
          if grep -r "import Papers.P3C_DCwAxis" Papers/P3_2CatFramework/; then
            echo "❌ ERROR: Found 3C imports in 3A!"
            exit 1
          fi
          echo "✅ 3A properly isolated from 3C"
      
      - name: Count sorries in 3C (informational)
        run: |
          echo "Counting sorries in Paper 3C (allowed in 3C):"
          grep -r "sorry" Papers/P3C_DCwAxis/ --include="*.lean" | wc -l || echo "0"
          echo "Note: sorries are allowed in 3C during development"